default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  port: 5432

development:
  <<: *default
  database: library_development

test:
  <<: *default
  database: library_test

# Docker
staging:
  <<: *default
  host:     <%= ENV['DB_HOST'] %>
  adapter:  <%= ENV['DB_ADAPTER'] || 'postgresql' %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>

# Docker
production:
  <<: *default
  host:     <%= ENV['DB_HOST'] %>
  adapter:  <%= ENV['DB_ADAPTER'] || 'postgresql' %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USER'] %>
  password: <%= ENV['DB_PASSWORD'] %>
